language: ruby
rvm:
- 2.2.2
addons:
  ssh_known_hosts:
  - "$WEB_SERVER"
script:
- bundle exec jekyll build
branches:
  only:
  - master
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
before_deploy:
- ssh-keyscan $WEB_SERVER >> ~/.ssh/known_hosts
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -i /tmp/deploy_rsa -r --delete-after _site/* $DEPLOY_USER@$WEB_SERVER:public_html/
  on:
    branch: master
cache: bundler
before_install:
- openssl aes-256-cbc -K $encrypted_31e1a3776c11_key -iv $encrypted_31e1a3776c11_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
