# Built with Jekyll 3.2.0

# Setup
title:               'slickrick.co'
tagline:             ''
description:         ''
url:                 'slickrick.co'
baseurl:             ''

# About/contact
author:
  name:              Erik Beerepoot 
  url:               https://www.linkedin.com/in/erik-beerepoot-1ab7083
  email:             e.b@nym.hush.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: Kramdown

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "hyde"


scholar:
  style: apa

start_line: 1

plugins:
        - jekyll-feed
        - jekyll-scholar
